name: React test validation

on: [pull_request]

jobs:
  react-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: cd thyrel-web && npm i
        env:
          CI: true
      - name: Test
        run: |
          cd thyrel-web && npm test --verbose --maxWorkers=2
        env:
          CI: true
  eslint-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # checkout to the repository
      - uses: actions/checkout@v1
      # install nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: cd thyrel-web && npm i
        working-directory: ${{env.working-directory}}
        env:
          CI: true
      - name: Run linter
        run: cd thyrel-web npm run gh:linter
        working-directory: ${{env.working-directory}}
        env:
          CI: true
